//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BggXMLDataReader
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoardGame
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoardGame()
        {
            this.BoardgameNome = new HashSet<BoardgameNome>();
        }
    
        public long ID { get; set; }
        public Nullable<int> ID_BGG { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> AnoPublicacao { get; set; }
        public Nullable<int> MinJogadores { get; set; }
        public Nullable<int> MaxJogadores { get; set; }
        public Nullable<int> TempoJogo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoardgameNome> BoardgameNome { get; set; }
    }
}
